spring.application.name=online-ordering

# ==========================
# SERVER
# ==========================
server.port=8080

# ==========================
# MySQL DATABASE
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/online_ordering_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# HIKARICP CONNECTION POOL
# ==========================
spring.datasource.hikari.pool-name=online_ordering_system
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=7
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=600000


# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# ==========================
# LOGGING
# ==========================
logging.level.root=INFO
#logging.level.com.example.onlineordering=DEBUG
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG



# ==========================
# APPLICATION CONFIGURATION
# ==========================
app.name=Online Ordering System
app.order.max-quantity=10

# ==========================
# FILE CONFIGURATION
# ==========================
app.file.invoice-directory=invoices
app.file.invoice-retention-seconds=20

# ==========================
# SPRINGDOC / SWAGGER
# ==========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==========================
# ACTUATOR
# ==========================
management.endpoints.web.exposure.include=*


# ==========================
# INVENTORY CONFIGURATION
# ==========================
app.inventory.low-stock-threshold=50

